---
kind: pipeline
type: docker
name: hello windows

clone:
  depth: 1

steps:
  - name: build
    image: registry.sean.farm/windows-2019-builder
    commands:
      - ls
      - make

platform:
  os: windows
  arch: amd64
        
image_pull_secrets:
  - dockerconfigjson
